### ISSUE TITLE
error: Operation not permitted when trying to rewrite a file

### ISSUE THREAD

**Issue by P-p-H-d** [TurboGit/hubicfuse#101] opened 2015-12-19 10:13 UTC
I get an error (operation not permitted) when trying to write to a file while the file already exists with hubicfuse as can be shown by the following operations:

mylogin@debian:/media/hubicfs/default/Documents$ ls -l
total 10300
-rw-rw-rw- 1 mylogin mylogin    57426 Dec 18 15:20 install
-rw-rw-rw- 1 mylogin mylogin 10485760 Dec 19 10:00 test
mylogin@debian:/media/hubicfs/default/Documents$ touch hello
ls mylogin@debian:/media/hubicfs/default/Documents$ ls -l
total 10300
-rw-rw-rw- 1 mylogin mylogin        0 Dec 19 10:56 hello
-rw-rw-rw- 1 mylogin mylogin    57426 Dec 18 15:20 install
-rw-rw-rw- 1 mylogin mylogin 10485760 Dec 19 10:00 test
mylogin@debian:/media/hubicfs/default/Documents$ echo hello > hello
bash: echo: write error: Operation not permitted
mylogin@debian:/media/hubicfs/default/Documents$ ls -l
total 10300
-rw-rw-rw- 1 mylogin mylogin        0 Dec 19 10:56 hello
-rw-rw-rw- 1 mylogin mylogin    57426 Dec 18 15:20 install
-rw-rw-rw- 1 mylogin mylogin 10485760 Dec 19 10:00 test
mylogin@debian:/media/hubicfs/default/Documents$ rm hello 
rm: remove regular empty file `hello'? y
mylogin@debian:/media/hubicfs/default/Documents$ echo hello > hello
mylogin@debian:/media/hubicfs/default/Documents$ ls -l
total 10304
-rw-rw-rw- 1 mylogin mylogin        6 Dec 19 10:57 hello
-rw-rw-rw- 1 mylogin mylogin    57426 Dec 18 15:20 install
-rw-rw-rw- 1 mylogin mylogin 10485760 Dec 19 10:00 test

Content of .hubicfuse is:

cache_timeout = 600
temp_dir = /tmp/
get_extended_metadata = true
curl_verbose = false
curl_progress_state = true
cache_statfs_timeout = 15
debug_level = 0
enable_chmod = false
enable_chown = false
verify_ssl=True

Extract of the log of hubicfuse:

flush[20363712]
==DBG 0 [2015-12-19 10:57:01.]:25506==cfs_flush(/default/Documents/hello)
==DBG 0 [2015-12-19 10:57:01.]:25506==cfs_flush(/default/Documents/hello): perform full upload as content changed (or no file found in cache)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    67  100    67    0     0    399      0 --:--:-- --:--:-- --:--:--   485
==DBG 0 [2015-12-19 10:57:01.]:25506==exit 0: send_request_size(/default?format=xml&delimiter=/&prefix=Documents_segments/) speed=0.2 sec (GET) [HTTP OK]
==DBG 0 [2015-12-19 10:57:02.]:25506==exit 0: send_request_size(/default/Documents/hello) speed=0.3 sec (PUT) [HTTP OK]
==DBG 0 [2015-12-19 10:57:02.]:25506==exit 1: cfs_flush(/default/Documents/hello) result=0:Success
   unique: 183, success, outsize: 16
unique: 184, opcode: WRITE (16), nodeid: 8, insize: 86, pid: 19142
write[20363712] 6 bytes to 0 flags: 0x8001
   unique: 184, error: -1 (Operation not permitted), outsize: 16
unique: 185, opcode: FLUSH (25), nodeid: 8, insize: 64, pid: 19142
flush[20363712]

**Comment by TurboGit** [comment] 2016-01-06 09:57
All this works on my side!

I have tried the above procedure and also with real content:

> $ echo toto > toto
> $ cat toto 
> toto
> $ echo titi > toto
> $ cat toto 
> titi

Even appending:

> $ echo tata >> toto
> $ cat toto
titi
tata

On Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux with fuse 2.9.4-1.

**Comment by P-p-H-d** [comment] 2016-01-06 13:10
Indeed. 
The above procedure now works for me (without any changes in the used tools).
I suppose the error was on the server side.

I have tried other variants and have found the the following procedure doesn't work as expected:

>$ rm hello
>$ echo hello > hello
>$ cat hello  # OK
>hello
>$ echo hello > hello
>$ cat hello  # OK
>hello
>$ echo hello >> hello
>$ cat hello  # OK
>hello
>hello
>$ echo hello >> hello
>$ cat hello  # OK
>hello
>hello
>hello
>$ echo hello > hello
>$ cat hello  # NOK: We should have only one "hello"
>hello
>hello
>hello
>$ echo test > hello
>$ cat hello  # NOK
>test
>
>hello
>hello

**Comment by Fibroblasto** [comment] 2016-10-26 10:04
I got exactly the same wrong behaviour reproducing the test of the last comment of P-p-H-d.

**Comment by Fibroblasto** [comment] 2016-12-23 15:46
Right now I get the same behaviour as the first post:

$ echo hello > hello
$ cat hello # OK
hello

$ echo hello > hello
bash: echo: write error: Operation not permitted

Content of ~/.hubicfuse is:

verify_ssl=true
segment_above=5368708096
temp_dir=/tmp

Debug output:

unique: 40, opcode: LOOKUP (1), nodeid: 1, insize: 48, pid: 29557
LOOKUP /default
getattr /default
==DBG 0 [2016-12-23 16:30:11.]:18542==cfs_getattr(/default)
==DBG 0 [2016-12-23 16:30:11.]:18542==exit 2: cfs_getattr(/default)
   NODEID: 2
   unique: 40, success, outsize: 144
unique: 41, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 29557
LOOKUP /default/hello
getattr /default/hello
==DBG 0 [2016-12-23 16:30:11.]:18543==cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 16:30:11.]:18543==exit 2: cfs_getattr(/default/hello)
   NODEID: 8
   unique: 41, success, outsize: 144
unique: 42, opcode: OPEN (14), nodeid: 8, insize: 48, pid: 29557
open flags: 0x8001 /default/hello
==DBG 0 [2016-12-23 16:30:11.]:18542==cfs_open(/default/hello)
==DBG 0 [2016-12-23 16:30:11.]:18542==exit 6: cfs_open(/default/hello)
   open[139981641437568] flags: 0x8001 /default/hello
   unique: 42, success, outsize: 32
unique: 43, opcode: SETATTR (4), nodeid: 8, insize: 128, pid: 29557
truncate /default/hello 0
==DBG 0 [2016-12-23 16:30:11.]:18543==cfs_truncate(/default/hello)
==DBG 0 [2016-12-23 16:30:17.]:18543==exit 0: send_request_size(/default/hello) speed=5.3 sec (PUT) [HTTP OK]
==DBG 0 [2016-12-23 16:30:17.]:18543==exit: cfs_truncate(/default/hello)
getattr /default/hello
==DBG 0 [2016-12-23 16:30:17.]:18543==cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 16:30:17.]:18543==exit 2: cfs_getattr(/default/hello)
   unique: 43, success, outsize: 120
unique: 44, opcode: FLUSH (25), nodeid: 8, insize: 64, pid: 29557
flush[139981641437568]
==DBG 0 [2016-12-23 16:30:17.]:18542==cfs_flush(/default/hello)
==DBG 0 [2016-12-23 16:30:17.]:18542==cfs_flush(/default/hello): skip full upload as content did not change
==DBG 0 [2016-12-23 16:30:19.]:18542==exit 0: send_request_size(/default/hello) speed=2.6 sec (PUT) [HTTP OK]
==DBG 0 [2016-12-23 16:30:19.]:18542==exit 1: cfs_flush(/default/hello) result=0:Success
   unique: 44, success, outsize: 16
unique: 45, opcode: WRITE (16), nodeid: 8, insize: 86, pid: 29557
write[139981641437568] 6 bytes to 0 flags: 0x8001
   unique: 45, error: -1 (Operation not permitted), outsize: 16
unique: 46, opcode: FLUSH (25), nodeid: 8, insize: 64, pid: 29557
flush[139981641437568]
==DBG 0 [2016-12-23 16:30:19.]:18542==cfs_flush(/default/hello)
==DBG 0 [2016-12-23 16:30:19.]:18542==cfs_flush(/default/hello): skip full upload as content did not change
==DBG 0 [2016-12-23 16:30:22.]:18542==exit 0: send_request_size(/default/hello) speed=2.5 sec (PUT) [HTTP OK]
==DBG 0 [2016-12-23 16:30:22.]:18542==exit 1: cfs_flush(/default/hello) result=0:Success
   unique: 46, success, outsize: 16
unique: 47, opcode: RELEASE (18), nodeid: 8, insize: 64, pid: 0
release[139981641437568] flags: 0x8001
==DBG 0 [2016-12-23 16:30:22.]:18543==cfs_release(/default/hello)
==DBG 0 [2016-12-23 16:30:22.]:18543==exit: cfs_release(/default/hello)
   unique: 47, success, outsize: 16

**Comment by TurboGit** [comment] 2016-12-23 16:00
Indeed, I can reproduce too!

**Comment by TurboGit** [comment] 2016-12-23 16:03
A one line reproducer:

> rm hello; echo 12345678 > hello ; echo 9876 > hello; cat hello

Looks like a fine is never resized down.

**Comment by TurboGit** [comment] 2016-12-23 20:14
I've just uploaded a fix: https://github.com/TurboGit/hubicfuse/commits/po/fix-truncate

Can someone review and test before I merge?

**Comment by Fibroblasto** [comment] 2016-12-23 20:47
It still doesn't allow to overwrite a file.

**Comment by TurboGit** [comment] 2016-12-23 20:54
@Fibroblasto, what do you mean? Can you show what is not working?

My message above works now as expected and does overwrite a file.

**Comment by Fibroblasto** [comment] 2016-12-23 21:02
$ echo hello > /mnt/hubic/default/hello
bash: echo: write error: Operation not permitted

Debug output:

unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 48, pid: 29557
LOOKUP /default
getattr /default
==DBG 0 [2016-12-23 21:57:36.]:21574==cfs_getattr(/default)
==DBG 0 [2016-12-23 21:57:36.]:21574==exit 0: send_request_size(/?format=xml) speed=0.4 sec (GET) [HTTP OK]
==DBG 0 [2016-12-23 21:57:36.]:21574==new_cache()
==DBG 0 [2016-12-23 21:57:36.]:21574==exit 2: cfs_getattr(/default)
   NODEID: 2
   unique: 2, success, outsize: 144
unique: 3, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 29557
LOOKUP /default/hello
getattr /default/hello
==DBG 0 [2016-12-23 21:57:36.]:21573==cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 21:57:36.]:21573==exit 0: send_request_size(/default?format=xml&delimiter=/&prefix=) speed=0.3 sec (GET) [HTTP OK]
==DBG 0 [2016-12-23 21:57:36.]:21573==new_cache(/default)
==DBG 0 [2016-12-23 21:57:36.]:21573==exit 2: cfs_getattr(/default/hello)
   NODEID: 3
   unique: 3, success, outsize: 144
unique: 4, opcode: OPEN (14), nodeid: 3, insize: 48, pid: 29557
open flags: 0x8001 /default/hello
==DBG 0 [2016-12-23 21:57:36.]:21574==cfs_open(/default/hello)
==DBG 0 [2016-12-23 21:57:36.]:21574==exit 6: cfs_open(/default/hello)
   open[140011974481120] flags: 0x8001 /default/hello
   unique: 4, success, outsize: 32
unique: 5, opcode: SETATTR (4), nodeid: 3, insize: 128, pid: 29557
truncate /default/hello 0
==DBG 0 [2016-12-23 21:57:36.]:21573==cfs_truncate(/default/hello) size=0
==DBG 0 [2016-12-23 21:57:37.]:21573==exit 0: send_request_size(/default/hello) speed=0.7 sec (PUT) [HTTP OK]
==DBG 0 [2016-12-23 21:57:37.]:21573==exit: cfs_truncate(/default/hello)
getattr /default/hello
==DBG 0 [2016-12-23 21:57:37.]:21573==cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 21:57:37.]:21573==exit 2: cfs_getattr(/default/hello)
   unique: 5, success, outsize: 120
unique: 6, opcode: FLUSH (25), nodeid: 3, insize: 64, pid: 29557
flush[140011974481120]
==DBG 0 [2016-12-23 21:57:37.]:21574==cfs_flush(/default/hello)
==DBG 0 [2016-12-23 21:57:37.]:21574==cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 21:57:37.]:21574==exit 2: cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 21:57:37.]:21574==cfs_flush(/default/hello): skip full upload as content did not change
==DBG 0 [2016-12-23 21:57:39.]:21574==exit 0: send_request_size(/default/hello) speed=1.6 sec (PUT) [HTTP OK]
==DBG 0 [2016-12-23 21:57:39.]:21574==exit 1: cfs_flush(/default/hello) result=0:Success
   unique: 6, success, outsize: 16
unique: 7, opcode: WRITE (16), nodeid: 3, insize: 86, pid: 29557
write[140011974481120] 6 bytes to 0 flags: 0x8001
   unique: 7, error: -1 (Operation not permitted), outsize: 16
unique: 8, opcode: FLUSH (25), nodeid: 3, insize: 64, pid: 29557
flush[140011974481120]
==DBG 0 [2016-12-23 21:57:39.]:21574==cfs_flush(/default/hello)
==DBG 0 [2016-12-23 21:57:39.]:21574==cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 21:57:39.]:21574==exit 2: cfs_getattr(/default/hello)
==DBG 0 [2016-12-23 21:57:39.]:21574==cfs_flush(/default/hello): skip full upload as content did not change
==DBG 0 [2016-12-23 21:57:40.]:21574==exit 0: send_request_size(/default/hello) speed=1.1 sec (PUT) [HTTP OK]
==DBG 0 [2016-12-23 21:57:40.]:21574==exit 1: cfs_flush(/default/hello) result=0:Success
   unique: 8, success, outsize: 16
unique: 9, opcode: RELEASE (18), nodeid: 3, insize: 64, pid: 0
release[140011974481120] flags: 0x8001
==DBG 0 [2016-12-23 21:57:40.]:21573==cfs_release(/default/hello)
==DBG 0 [2016-12-23 21:57:40.]:21573==exit: cfs_release(/default/hello)
   unique: 9, success, outsize: 16

**Comment by TurboGit** [comment] 2016-12-23 21:10
I see, but I cannot reproduce this. And you can see this has my fix does overwrite a file.

So you'll have to debug this or at least found a reproducer.

For example what is the permissions on the file?

> $ ls /mnt/hubic/default/hello

Does it happens if you create another file or is this specific to this file?

Also can you try without "get_extended_metadata = true" in your .hubicfuse?

How do you mount your hubic fuse?

I also suppose that you don't have only the listed options in your .hubicfuse, right? (what about the refresh_token, client_id and client_secret?)

**Comment by TurboGit** [comment] 2016-12-23 21:22
And when I say I cannot reproduce it is not only with the simple example posted here. I have in the last 4 days copied over more than 5000 files to my hubic account and I do suppose many other people don't have this issue either.

**Comment by Fibroblasto** [comment] 2016-12-23 21:43
The permissions are “rw-” for everybody.

The same if I create a new file.

I did not have "get_extended_metadata" in .hubicfuse. Now, Y have tried with "get_extended_metadata=true" and "get_extended_metadata=false". The same result.

Mount command: hubicfuse  /mnt/hubic -o noauto_cache,sync_read,allow_other

Of course, I have set refresh_token, client_id and client_secret. Otherwise I suppose I could not even mount it and list the files.

**Comment by TurboGit** [comment] 2016-12-23 21:46
Can you try with:

> hubicfuse /mnt/hubic -o noauto,noauto_cache,sync_read,user,allow_other

**Comment by TurboGit** [comment] 2016-12-23 21:48
> Of course, I have set refresh_token, client_id and client_secret. Otherwise I suppose I could not even mount it and list the files.

Or you would have been looking at the .hutbicfuse in a user's home instead of root or vis-versa, I did that when debugging and was puzzled :)

**Comment by Fibroblasto** [comment] 2016-12-23 21:59
> Can you try with:
> 
>     hubicfuse /mnt/hubic -o noauto,noauto_cache,sync_read,user,allow_other
> 

Not possible: “fuse: unknown option `noauto'” or “fuse: unknown option `user'”. In fact. “user” and “noauto” don't make any sense in the command line, only in fstab they make sense.

**Comment by TurboGit** [comment] 2016-12-23 22:08
Indeed, I thought about the fstab options, as this is what I have on my side.

And what if you run as sudo:

> sudo hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other

**Comment by TurboGit** [comment] 2016-12-23 22:14
Just tried again:

> $ hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
> $  cd /mnt/hubic/default/testing/
> $ touch newfile
> $ ls -al
> total 4
> drwxr-xr-x 2 obry obry 0 Dec 23 16:54 .
> drwxr-xr-x 2 obry obry 0 Dec 23 23:08 ..
> -rw-rw-rw- 1 obry obry 0 Dec 23 23:11 newfile
> $ cat newfile 
> $ echo toto > newfile 
> $ cat newfile 
> toto

**Comment by Fibroblasto** [comment] 2016-12-23 22:29
> sudo hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other

The same using sudo. 

What about if the libraries in my system that were used to compile the program were not the right version? My system is Debian stable. Could I try to use your compiled binary?

**Comment by TurboGit** [comment] 2016-12-24 11:30
That's not a solution as hubicfuse is built with shared libraries.

One more question, when you have generated your refresh_token with the hubic_token script, have you properly entered the permissions as described in parentheses? Did you change them? This could just be a basic permission issue.

**Comment by Fibroblasto** [comment] 2016-12-24 11:39
> That's not a solution as hubicfuse is built with shared libraries.

That's what I wonder. If the problem would be in the shared libraries.

> One more question, when you have generated your refresh_token with the hubic_token script, have you properly entered the permissions as described in parentheses? Did you change them? This could just be a basic permission issue.

I don't remember how I did it. I just followed the procedure. I will repeat it again just in case.

**Comment by TurboGit** [comment] 2016-12-24 11:42
Yes and be sure to enter exactly the proposed permissions.

**Comment by TurboGit** [comment] 2016-12-24 11:45
@Fibroblasto but because there is lot of shared libraries having just the hubicfuse binary won't help. You'll also need all the shared libraries. But I'm on Debian/sid, no chance the binary to work on Debian/stable I think. For reference, here are all the shared libs I'm using:

> $ ldd ./hubicfuse 
>	linux-vdso.so.1 (0x00007ffe603fd000)
>	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f2696d44000)
>	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f2696ac9000)
>	libfuse.so.2 => /lib/x86_64-linux-gnu/libfuse.so.2 (0x00007f269688b000)
>	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f2696620000)
>	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f269618f000)
>	libjson-c.so.3 => /lib/x86_64-linux-gnu/libjson-c.so.3 (0x00007f2695f82000)
>	libmagic.so.1 => /usr/lib/x86_64-linux-gnu/libmagic.so.1 (0x00007f2695d60000)
>	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2695b43000)
>	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f26957a5000)
>	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f26955a1000)
>	libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007f2695127000)
>	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f2694d7d000)
>	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f2693300000)
>	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f26930e6000)
>	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2692ec0000)
>	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2692bbc000)
>	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f2692996000)
>	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f2692777000)
>	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f269254b000)
>	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f2692314000)
>	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f2691f7c000)
>	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f2691d31000)
>	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f2691a57000)
>	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f2691822000)
>	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f269161e000)
>	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f269140f000)
>	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f26911be000)
>	/lib64/ld-linux-x86-64.so.2 (0x0000559f0978b000)
>	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2690e3c000)
>	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2690c23000)
>	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f26909ee000)
>	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f269076b000)
>	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f269045b000)
>	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f26901f6000)
>	libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007f268ffc0000)
>	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f268fdad000)
>	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f268fba1000)
>	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f268f99d000)
>	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f268f786000)
>	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f268f569000)
>	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f268f355000)
>	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f268f14c000)

**Comment by Fibroblasto** [comment] 2016-12-24 15:13
I have an old install of Debian Sid using Virtualbox. If other things fail I'll try to install Hubicfuse there.

**Comment by Fibroblasto** [comment] 2016-12-26 01:57
I've fount it!!!

It was the line “temp_dir=/tmp” in ~/.hubicfuse. The problem is solved removing that line. It was my fault: the first thing I should have tried was to remove all the lines in .hubicfuse but the three necessary to connect. Maybe you want to do something about that option.

Thanks a lot fos the time you have spend with this.

I've tried with Borg backup and it worked without errors. Anyway, the performance was quite poor compared with Yandex-disk, that is connected using webdav and mounted with davfs. It takes a hell till it asks me the password and and then it uploads and downloads a lot in a backup update that should upload only 441 bytes. Is there any option to improve the performance? Anyway, the performance should be the subject of another issue.

**Comment by TurboGit** [comment] 2016-12-26 10:45
Good to hear! For the performance I doubt something can be done, this is mostly what HubiC architecture propose. Il also all depends on your upload speed. I have myself a max of 100kb/s upload and I do upload at max speed with HubiC.
Anyway closing this ticket.

**Closed by TurboGit** 2016-12-26 10:45 UTC
Labels: bug
